import axios from 'axios'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { addData } from './features/ipAddressDetailsSlice'
import './App.css'

function App() {
  const ipAddress = useSelector((state) => {
    return state.ipAddressData.value
  })
  const dispatch = useDispatch()

  useEffect(() => {
    getData()
  }, [])

  // inside [] : If you don't add anything inside, it will work only 1 time.

  async function getData() {
    const data = await axios.get(
      'https://geo.ipify.org/api/v2/country?apiKey=at_lWM01gz3Ta7jyqG1QFsPMj5l1mFty&ipAddress=8.8.8.8'
    )
    dispatch(addData(data.data))
  }

  console.log(ipAddress)

  return (
    <div className="App">
      <h1>IP Address Tracker</h1>
      <br />
      <table>
        <tbody>
          <tr>
            <th>IP ADDRESS</th>
            <th>LOCATION</th>
            <th>TIMEZONE</th>
            <th>ISP</th>
          </tr>
          <tr>
            <td>{ipAddress.ip}</td>
            <td>{`${ipAddress?.location?.country}, ${ipAddress?.location?.region}`}</td>
            <td>{ipAddress?.location?.timezone}</td>
            <td>{ipAddress?.isp}</td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}

export default App

// Line 22 : Found an error "<tr> cannot appear as a child of <table>.
// Add a <tbody>, <thead> or <tfoot> to your code
// to match the DOM tree generated by the browser."
